<?php

declare(strict_types=1);

namespace App\Actions\Auth;

use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Find-or-create a user from a verified Telegram payload.
 *
 * New users get telegram_id + first_name only — username and pin_hash stay
 * null until the user completes /auth/setup-pin. The wallet_code is
 * auto-generated by the User::creating model event.
 */
final class RegisterWithTelegramAction
{
    public function execute(TelegramPayload $payload): User
    {
        return DB::transaction(function () use ($payload): User {
            $existing = User::query()->where('telegram_id', $payload->id)->first();

            if ($existing !== null) {
                Log::channel('audit')->info('auth.telegram.success', [
                    'user_id' => $existing->id,
                    'new_account' => false,
                    'ip' => request()?->ip(),
                ]);

                return $existing;
            }

            $user = User::create([
                'telegram_id' => $payload->id,
                'name' => $payload->firstName !== '' ? $payload->firstName : null,
                'status' => 'active',
            ]);

            $user->wallet()->create([
                'balance' => '0.00',
                'held_balance' => '0.00',
                'version' => 0,
            ]);

            Log::channel('audit')->info('auth.telegram.success', [
                'user_id' => $user->id,
                'new_account' => true,
                'ip' => request()?->ip(),
            ]);

            return $user;
        });
    }
}
